<a href="https://colab.research.google.com/github/FerDev5432/repositorio-python/blob/master/ABCanalisisDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

index_col="id", hace que pandas ua no cree otra linea que cuente las columnas aso 0,1,2,... si no que con este parametro entiendo que esa columna sera para identificar

In [6]:
df = pd.read_csv("dataset.csv")
df

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
6,183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
12,183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
13,183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258
14,183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
16,183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
17,183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
18,183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378
19,183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
20,183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
21,183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
23,183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
25,183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

In [5]:
df = pd.read_csv("dataset.csv", index_col="id")
df

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129
183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822
183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,BRASIL,mateusmartins,982.0,1822
183732,Its been in love with the game with the origin...,349.0,44.0,19.0,BRASIL,mateusmartins,982.0,1822
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183734,I cannot believe this!,50.0,24.0,22.0,ECUADOR,leonardokuffo,389.0,258
183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,MEXICO,pedrojuarez,12.0,129
183737,PIC!!,346.0,115.0,24.0,BRASIL,lucasperes,82.0,351
183738,hmmm feeling bad today,296.0,93.0,29.0,MEXICO,gabrielcarvajal,21.0,2721
183739,not feeling god right now,315.0,26.0,10.0,ECUADOR,galocastillo,332.0,378
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378
183742,WHAT???,255.0,73.0,17.0,ECUADOR,galocastillo,332.0,378
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721
183747,I do not know if i like programming or other t...,318.0,58.0,20.0,BRASIL,isabelladasilva,928.0,9918

Funcion head - muestra primeras 5 filas y tail 5 ultimas, pero tambien si le pasas un valor ejemplo df.head() solo muestra 5, df.head(10) muestra 10, mismo caso con tail

In [8]:
df.head()

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

In [11]:
df.head(10)

,id,full_text,favorites,retweets,mentions,country,user,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
6,183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,MEXICO,pedrojuarez,12.0,129
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,MEXICO,pedrojuarez,12.0,129
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,BRASIL,mateusmartins,982.0,1822

Con la funcion describe nos va a dar estadistica descriptiva acerca del dataframe original, ejemplo cuenta los campos, media, moda, mediana, etc

In [14]:
df = pd.read_csv("dataset.csv", index_col="id")
df.describe()

        favorites    retweets   mentions   followers    followees
count   26.000000   26.000000  26.000000   26.000000    27.000000
mean   280.538462   80.000000  15.423077  352.807692  1190.185185
std    153.377242   40.303846   9.596554  375.319493  1965.735995
min     23.000000   21.000000   1.000000   12.000000   129.000000
25%    139.250000   45.500000   8.250000   21.000000   258.000000
50%    305.500000   79.000000  16.000000  332.000000   351.000000
75%    422.500000  110.750000  23.500000  389.000000  1822.000000
max    500.000000  146.000000  29.000000  982.000000  9918.000000

Limpieza de datos
1. dropna: elimina registros o filas que tengan valores nulos o NaN
2. fillna(0): llena los espacios de valor NaN con un 0, pero tambien se pueden llenar los campos con valores especificos fillna({"columna":valor})

In [15]:
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

In [18]:
df_filtrado = df.dropna()
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183727,80's & friends! ✈️,158.0,40.0,22.0,ECUADOR,leonardokuffo,389.0,258

In [19]:
df_filtrado = df.fillna(0)
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,0.0,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

In [20]:
df_filtrado=df.fillna({"retweets":0, "mentions":-1})
df_filtrado.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,0.0,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,-1.0,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129

Filtrado de datos
* filtrar columnas -> df["columna"] -> df["Columna1", "Columna2"]
* filtrar filas con indices 0,1,2,...-> df.iloc[indice] ej df.iloc[0] -> df.iloc[indice_inicio: indice_fin] -> df.iloc[indice1, indice2, indice3]
* filtrar filas con columnas del dataframe -> df.loc[id1, id2]

In [21]:
df["full_text"]

id
183721    Flying home to run down from the power to comi...
183722                  Today we commemorate and MNML Case.
183723         Today we have reached US$6.55 Billion TT$44…
183724    Faking It by Joel Atwell. Written by Other cou...
183725                                      Welcome back! 🙌
183726    Contest: Win a fan of his ass. #thatisall Thanks!
183727                                   80's & friends! ✈️
183728    Thank you guess how did I feel somewhat offend...
183729          OnePlus 8 international giveaway classifies
183730                  Here it is.. Retweet this desperate
183731    Great to advertise during the year I tweeted a...
183732    Its been in love with the game with the origin...
183733                             Programming is the best!
183734                               I cannot believe this!
183735                               Buy this product NOW!!
183736    I have one is best color gradients: Just relea...
183737                                                PIC!!
183738                               hmmm feeling bad today
183739                            not feeling god right now
183740                          Programming is a hot topic!
183741                              Programming? i love it!
183742                                              WHAT???
183743                           Amazing video by Leonardo!
183744                                          Thanks man!
183745            There is nothing better than programming!
183746                                             BORED AF
183747    I do not know if i like programming or other t...
Name: full_text, dtype: object

In [22]:
df[["favorites","full_text"]]

        favorites                                          full_text
id
183721       23.0  Flying home to run down from the power to comi...
183722      500.0                Today we commemorate and MNML Case.
183723      190.0       Today we have reached US$6.55 Billion TT$44…
183724      131.0  Faking It by Joel Atwell. Written by Other cou...
183725      113.0                                    Welcome back! 🙌
183726      492.0  Contest: Win a fan of his ass. #thatisall Thanks!
183727      158.0                                 80's & friends! ✈️
183728        NaN  Thank you guess how did I feel somewhat offend...
183729      198.0        OnePlus 8 international giveaway classifies
183730      272.0                Here it is.. Retweet this desperate
183731       43.0  Great to advertise during the year I tweeted a...
183732      349.0  Its been in love with the game with the origin...
183733      467.0                           Programming is the best!
183734       50.0                             I cannot believe this!
183735      418.0                             Buy this product NOW!!
183736      361.0  I have one is best color gradients: Just relea...
183737      346.0                                              PIC!!
183738      296.0                             hmmm feeling bad today
183739      315.0                          not feeling god right now
183740      133.0                        Programming is a hot topic!
183741       92.0                            Programming? i love it!
183742      255.0                                            WHAT???
183743      432.0                         Amazing video by Leonardo!
183744      430.0                                        Thanks man!
183745      424.0          There is nothing better than programming!
183746      488.0                                           BORED AF
183747      318.0  I do not know if i like programming or other t...

In [23]:
df.iloc[0]

full_text    Flying home to run down from the power to comi...
favorites                                                 23.0
retweets                                                   NaN
mentions                                                  10.0
country                                                ECUADOR
user                                             leonardokuffo
followers                                                389.0
followees                                                  258
Name: 183721, dtype: object

In [24]:
df.iloc[0:4]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378

In [26]:
df.iloc[[0,1,2]]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129

In [27]:
df.loc[[183721,183723]]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129

Filtrar filas y columnas
* Funcion loc[[filtradoFilas],[filtradoColumnas]] -> df.loc[[num1,num2],["campo1","campo2"]]

In [28]:
df.loc[[183721,183722], ["full_text", "favorites"]]

                                                full_text  favorites
id
183721  Flying home to run down from the power to comi...       23.0
183722                Today we commemorate and MNML Case.      500.0

Filtrado por condiciones
* df[df["campo"]>400] del campo dame los que cumplan la condicion mayor que 400

en pandas el and se representa como & y el or |

In [29]:
df[df["favorites"]>400]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822
183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,BRASIL,mateusmartins,982.0,1822
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183735,Buy this product NOW!!,418.0,24.0,2.0,MEXICO,gabrielcarvajal,21.0,2721
183743,Amazing video by Leonardo!,432.0,95.0,18.0,BRASIL,lucasperes,82.0,351
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721

In [30]:
df[(df["favorites"]>400) &(df["mentions"]>20)]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183744,Thanks man!,430.0,143.0,28.0,BRASIL,lucasperes,NaN,351
183745,There is nothing better than programming!,424.0,110.0,29.0,BRASIL,lucasperes,82.0,351
183746,BORED AF,488.0,28.0,27.0,MEXICO,gabrielcarvajal,21.0,2721

.str.contains("Subcadena") - busca en el campo los valores que contengan la subcadena

In [31]:
df[df["full_text"].str.contains("Programming")]

,full_text,favorites,retweets,mentions,country,user,followers,followees
id,,,,,,,,
183733,Programming is the best!,467.0,69.0,10.0,ECUADOR,leonardokuffo,389.0,258
183740,Programming is a hot topic!,133.0,145.0,15.0,BRASIL,lucasperes,82.0,351
183741,Programming? i love it!,92.0,146.0,1.0,ECUADOR,galocastillo,332.0,378

Transformacion de datos
* Para campos nuevos, calculados en base a otros campos
df["campoNuevo"] = df["campoAlQueSeLeAplicaLaFuncion"].apply(Funcion)


para cada valor del campo, aplicale la funcion y lo que retorne almacenalo en el campoNuevo

Funcion para calcular ganancias: toma el valor de los retweets y lo multiplica por un numero random entre 3 y 5

In [35]:
import random
from numpy import random

def calcularGanancias(retweets):
  ganancia= retweets * random.randint(3,5)
  return ganancia

df["ganancias"] = df["retweets"].apply(calcularGanancias)
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees,ganancias
id,,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258,NaN
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822,84.0
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129,492.0
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378,228.0
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129,520.0

In [37]:
def popularidad(fila):
  resultado=fila["followees"]/fila["followers"]
  return resultado

df["popularidad"] = df.apply(popularidad, axis=1)
df.head()

,full_text,favorites,retweets,mentions,country,user,followers,followees,ganancias,popularidad
id,,,,,,,,,,
183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,ECUADOR,leonardokuffo,389.0,258,NaN,0.663239
183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,BRASIL,mateusmartins,982.0,1822,84.0,1.855397
183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,MEXICO,pedrojuarez,12.0,129,492.0,10.750000
183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,ECUADOR,galocastillo,332.0,378,228.0,1.138554
183725,Welcome back! 🙌,113.0,130.0,9.0,MEXICO,pedrojuarez,12.0,129,520.0,10.750000

Agrupacion de datos
* df.funcionGroupby("campo").funcionAgrupacion()

In [42]:
df[['country', 'favorites', 'retweets', 'mentions', 'followers', 'followees', 'ganancias', 'popularidad']].groupby("country").mean()

,favorites,retweets,mentions,followers,followees,ganancias,popularidad
country,,,,,,,
BRASIL,339.909091,91.272727,19.600,616.600,1889.363636,308.000000,3.708644
ECUADOR,186.375000,64.857143,11.875,360.500,318.000000,218.285714,0.900897
MEXICO,294.857143,77.750000,13.750,15.375,1101.000000,296.000000,55.308036

* agrupacion de varios campos: agrupando el campo de country, aplica a las columnas diferentes metodos
df.Groupby("Campo").agg({"campo1":funcion, "campoN":funcion})

In [44]:
df.groupby("country").agg({
    "followers": 'sum',
    "mentions": 'mean',
    "retweets": 'max'
})

         followers  mentions  retweets
country
BRASIL      6166.0    19.600     145.0
ECUADOR     2884.0    11.875     146.0
MEXICO       123.0    13.750     130.0

Guardado de datos
Pasar de una dataframe creado a un archivo
1. Hacemos una variable que almacene el dataframe
2. NombreDataFrame.to_csv() -> variantes to_json,to_html,to_sql,etc

In [45]:
grouped= df.groupby("country").agg({
    "followers": 'sum',
    "mentions": 'mean',
    "retweets": 'max'
})
grouped

         followers  mentions  retweets
country
BRASIL      6166.0    19.600     145.0
ECUADOR     2884.0    11.875     146.0
MEXICO       123.0    13.750     130.0

In [47]:
grouped.to_csv("Salida.csv")