<a href="https://colab.research.google.com/github/FerDev5432/repositorio-python/blob/master/Joins_Fechas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Joins - unir varios dataframes en uno solo

En este escenario tenemos 3 diferentes dataframes, pero buscamos la forma en como se relacionan todos tenemos columnas como usuario y ciudad que se encuentran como relaciones, a partir de aqui vamos a trabajar

In [5]:
import pandas as pd

In [6]:
#carga datos
df1 = pd.read_csv("dataset_2a.csv")
df2 = pd.read_csv("dataset_2b.csv")
df3 = pd.read_csv("dataset_2c.csv")

In [7]:
df1

,id,full_text,favorites,retweets,mentions,user,fecha_publicado
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,mateusmartins,29/01/2023
6,183727,80's & friends! ✈️,158.0,40.0,22.0,leonardokuffo,29/01/2023
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,pedrojuarez,29/01/2023
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,pedrojuarez,30/01/2023
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,mateusmartins,31/01/2023
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,mateusmartins,31/01/2023
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,mateusmartins,31/01/2023
12,183733,Programming is the best!,467.0,69.0,10.0,leonardokuffo,01/02/2023
13,183734,I cannot believe this!,50.0,24.0,22.0,leonardokuffo,01/02/2023
14,183735,Buy this product NOW!!,418.0,24.0,2.0,gabrielcarvajal,01/02/2023
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,pedrojuarez,02/02/2023
16,183737,PIC!!,346.0,115.0,24.0,lucasperes,03/02/2023
17,183738,hmmm feeling bad today,296.0,93.0,29.0,gabrielcarvajal,04/02/2023
18,183739,not feeling god right now,315.0,26.0,10.0,galocastillo,05/02/2023
19,183740,Programming is a hot topic!,133.0,145.0,15.0,lucasperes,05/02/2023
20,183741,Programming? i love it!,92.0,146.0,1.0,galocastillo,05/02/2023
21,183742,WHAT???,255.0,73.0,17.0,galocastillo,05/02/2023
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,lucasperes,06/02/2023
23,183744,Thanks man!,430.0,143.0,28.0,lucasperes,07/02/2023
24,183745,There is nothing better than programming!,424.0,110.0,29.0,lucasperes,02/03/2023
25,183746,BORED AF,488.0,28.0,27.0,gabrielcarvajal,02/03/2023
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,isabelladasilva,03/03/2023

In [8]:
df2

           ciudad  followers  followees             user
0       GUAYAQUIL      389.0        258    leonardokuffo
1       SAO PAULO      982.0       1822    mateusmartins
2          OAXACA       12.0        129      pedrojuarez
3           QUITO      332.0        378     galocastillo
4     GUADALAJARA       21.0       2721  gabrielcarvajal
5  RIO DE JANEIRO       82.0        351       lucasperes
6    PORTO ALEGRE      928.0       9918  isabelladasilva

In [9]:
df3

           ciudad     pais
0       GUAYAQUIL  ECUADOR
1  RIO DE JANEIRO   BRASIL
2     GUADALAJARA   MEXICO
3          OAXACA   MEXICO
4           QUITO  ECUADOR
5       SAO PAULO   BRASIL
6  BELO HORIZONTE   BRASIL

Para unir dataframes se hace como una analogia el dataframe principal sera el de la izquierda mientras que el de la derecha sera como un complemento

nombreDataframe1.merge(nombreDataframe2, on"CampoDeRelacion", how="tipoDeJoin")
en el tipo de join puede ir inner, left, right, dependiendo el caso de uso

In [10]:
df_con_usuarios= df1.merge(df2, on='user', how="left")
df_con_usuarios

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,mateusmartins,29/01/2023,SAO PAULO,982.0,1822
6,183727,80's & friends! ✈️,158.0,40.0,22.0,leonardokuffo,29/01/2023,GUAYAQUIL,389.0,258
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,pedrojuarez,29/01/2023,OAXACA,12.0,129
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,pedrojuarez,30/01/2023,OAXACA,12.0,129
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822
12,183733,Programming is the best!,467.0,69.0,10.0,leonardokuffo,01/02/2023,GUAYAQUIL,389.0,258
13,183734,I cannot believe this!,50.0,24.0,22.0,leonardokuffo,01/02/2023,GUAYAQUIL,389.0,258
14,183735,Buy this product NOW!!,418.0,24.0,2.0,gabrielcarvajal,01/02/2023,GUADALAJARA,21.0,2721
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,pedrojuarez,02/02/2023,OAXACA,12.0,129
16,183737,PIC!!,346.0,115.0,24.0,lucasperes,03/02/2023,RIO DE JANEIRO,82.0,351
17,183738,hmmm feeling bad today,296.0,93.0,29.0,gabrielcarvajal,04/02/2023,GUADALAJARA,21.0,2721
18,183739,not feeling god right now,315.0,26.0,10.0,galocastillo,05/02/2023,QUITO,332.0,378
19,183740,Programming is a hot topic!,133.0,145.0,15.0,lucasperes,05/02/2023,RIO DE JANEIRO,82.0,351
20,183741,Programming? i love it!,92.0,146.0,1.0,galocastillo,05/02/2023,QUITO,332.0,378
21,183742,WHAT???,255.0,73.0,17.0,galocastillo,05/02/2023,QUITO,332.0,378
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,lucasperes,06/02/2023,RIO DE JANEIRO,82.0,351
23,183744,Thanks man!,430.0,143.0,28.0,lucasperes,07/02/2023,RIO DE JANEIRO,82.0,351
24,183745,There is nothing better than programming!,424.0,110.0,29.0,lucasperes,02/03/2023,RIO DE JANEIRO,82.0,351
25,183746,BORED AF,488.0,28.0,27.0,gabrielcarvajal,02/03/2023,GUADALAJARA,21.0,2721
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,isabelladasilva,03/03/2023,PORTO ALEGRE,928.0,9918

In [11]:
df_completo = df_con_usuarios.merge(df3, on='ciudad', how="left")
df_completo

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,mateusmartins,29/01/2023,SAO PAULO,982.0,1822,BRASIL
6,183727,80's & friends! ✈️,158.0,40.0,22.0,leonardokuffo,29/01/2023,GUAYAQUIL,389.0,258,ECUADOR
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,pedrojuarez,29/01/2023,OAXACA,12.0,129,MEXICO
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,pedrojuarez,30/01/2023,OAXACA,12.0,129,MEXICO
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822,BRASIL
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822,BRASIL
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822,BRASIL
12,183733,Programming is the best!,467.0,69.0,10.0,leonardokuffo,01/02/2023,GUAYAQUIL,389.0,258,ECUADOR
13,183734,I cannot believe this!,50.0,24.0,22.0,leonardokuffo,01/02/2023,GUAYAQUIL,389.0,258,ECUADOR
14,183735,Buy this product NOW!!,418.0,24.0,2.0,gabrielcarvajal,01/02/2023,GUADALAJARA,21.0,2721,MEXICO
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,pedrojuarez,02/02/2023,OAXACA,12.0,129,MEXICO
16,183737,PIC!!,346.0,115.0,24.0,lucasperes,03/02/2023,RIO DE JANEIRO,82.0,351,BRASIL
17,183738,hmmm feeling bad today,296.0,93.0,29.0,gabrielcarvajal,04/02/2023,GUADALAJARA,21.0,2721,MEXICO
18,183739,not feeling god right now,315.0,26.0,10.0,galocastillo,05/02/2023,QUITO,332.0,378,ECUADOR
19,183740,Programming is a hot topic!,133.0,145.0,15.0,lucasperes,05/02/2023,RIO DE JANEIRO,82.0,351,BRASIL
20,183741,Programming? i love it!,92.0,146.0,1.0,galocastillo,05/02/2023,QUITO,332.0,378,ECUADOR
21,183742,WHAT???,255.0,73.0,17.0,galocastillo,05/02/2023,QUITO,332.0,378,ECUADOR
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,lucasperes,06/02/2023,RIO DE JANEIRO,82.0,351,BRASIL
23,183744,Thanks man!,430.0,143.0,28.0,lucasperes,07/02/2023,RIO DE JANEIRO,82.0,351,BRASIL
24,183745,There is nothing better than programming!,424.0,110.0,29.0,lucasperes,02/03/2023,RIO DE JANEIRO,82.0,351,BRASIL
25,183746,BORED AF,488.0,28.0,27.0,gabrielcarvajal,02/03/2023,GUADALAJARA,21.0,2721,MEXICO
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,isabelladasilva,03/03/2023,PORTO ALEGRE,928.0,9918,NaN

Generalmente las fechas estan como tipo de dato STR, pero lo ideal es tenerlas en formato de tipo fecha
dataframeNombre['campoFecha'] = pd.to_datetime(dataframeNombre['columna_fecha'],formatoFecha)

In [12]:
df_completo['fecha'] = pd.to_datetime(df_completo['fecha_publicado'], format="%d/%m/%Y")
df_completo

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais,fecha
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-27
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-27
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR,2023-01-28
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,mateusmartins,29/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-29
6,183727,80's & friends! ✈️,158.0,40.0,22.0,leonardokuffo,29/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-29
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,pedrojuarez,29/01/2023,OAXACA,12.0,129,MEXICO,2023-01-29
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,pedrojuarez,30/01/2023,OAXACA,12.0,129,MEXICO,2023-01-30
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-31
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-31
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-31
12,183733,Programming is the best!,467.0,69.0,10.0,leonardokuffo,01/02/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-02-01
13,183734,I cannot believe this!,50.0,24.0,22.0,leonardokuffo,01/02/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-02-01
14,183735,Buy this product NOW!!,418.0,24.0,2.0,gabrielcarvajal,01/02/2023,GUADALAJARA,21.0,2721,MEXICO,2023-02-01
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,pedrojuarez,02/02/2023,OAXACA,12.0,129,MEXICO,2023-02-02
16,183737,PIC!!,346.0,115.0,24.0,lucasperes,03/02/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-02-03
17,183738,hmmm feeling bad today,296.0,93.0,29.0,gabrielcarvajal,04/02/2023,GUADALAJARA,21.0,2721,MEXICO,2023-02-04
18,183739,not feeling god right now,315.0,26.0,10.0,galocastillo,05/02/2023,QUITO,332.0,378,ECUADOR,2023-02-05
19,183740,Programming is a hot topic!,133.0,145.0,15.0,lucasperes,05/02/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-02-05
20,183741,Programming? i love it!,92.0,146.0,1.0,galocastillo,05/02/2023,QUITO,332.0,378,ECUADOR,2023-02-05
21,183742,WHAT???,255.0,73.0,17.0,galocastillo,05/02/2023,QUITO,332.0,378,ECUADOR,2023-02-05
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,lucasperes,06/02/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-02-06
23,183744,Thanks man!,430.0,143.0,28.0,lucasperes,07/02/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-02-07
24,183745,There is nothing better than programming!,424.0,110.0,29.0,lucasperes,02/03/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-03-02
25,183746,BORED AF,488.0,28.0,27.0,gabrielcarvajal,02/03/2023,GUADALAJARA,21.0,2721,MEXICO,2023-03-02
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,isabelladasilva,03/03/2023,PORTO ALEGRE,928.0,9918,NaN,2023-03-03

Ejemplo: Quiero saber que dia de la semana es una fecha en especifico
Para cada valor de columnaConFormatoFecha se le va a aplicar la funcion strftime que convierte el formato fecha en un str y %A solo nos dara el dia.
nombreDataFrame[nombreColumna] = df['columnaConFormatoFecha'].apply(lambda x:x.strftime('%A'))

In [13]:
df_completo['dia_semana'] = df_completo['fecha'].apply(lambda x:x.strftime('%A'))
df_completo

,id,full_text,favorites,retweets,mentions,user,fecha_publicado,ciudad,followers,followees,pais,fecha,dia_semana
0,183721,Flying home to run down from the power to comi...,23.0,NaN,10.0,leonardokuffo,27/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-27,Friday
1,183722,Today we commemorate and MNML Case.,500.0,21.0,NaN,mateusmartins,27/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-27,Friday
2,183723,Today we have reached US$6.55 Billion TT$44…,190.0,123.0,6.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday
3,183724,Faking It by Joel Atwell. Written by Other cou...,131.0,76.0,3.0,galocastillo,28/01/2023,QUITO,332.0,378,ECUADOR,2023-01-28,Saturday
4,183725,Welcome back! 🙌,113.0,130.0,9.0,pedrojuarez,28/01/2023,OAXACA,12.0,129,MEXICO,2023-01-28,Saturday
5,183726,Contest: Win a fan of his ass. #thatisall Thanks!,492.0,70.0,6.0,mateusmartins,29/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-29,Sunday
6,183727,80's & friends! ✈️,158.0,40.0,22.0,leonardokuffo,29/01/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-01-29,Sunday
7,183728,Thank you guess how did I feel somewhat offend...,NaN,50.0,10.0,pedrojuarez,29/01/2023,OAXACA,12.0,129,MEXICO,2023-01-29,Sunday
8,183729,OnePlus 8 international giveaway classifies,198.0,82.0,26.0,pedrojuarez,30/01/2023,OAXACA,12.0,129,MEXICO,2023-01-30,Monday
9,183730,Here it is.. Retweet this desperate,272.0,92.0,29.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-31,Tuesday
10,183731,Great to advertise during the year I tweeted a...,43.0,111.0,8.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-31,Tuesday
11,183732,Its been in love with the game with the origin...,349.0,44.0,19.0,mateusmartins,31/01/2023,SAO PAULO,982.0,1822,BRASIL,2023-01-31,Tuesday
12,183733,Programming is the best!,467.0,69.0,10.0,leonardokuffo,01/02/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-02-01,Wednesday
13,183734,I cannot believe this!,50.0,24.0,22.0,leonardokuffo,01/02/2023,GUAYAQUIL,389.0,258,ECUADOR,2023-02-01,Wednesday
14,183735,Buy this product NOW!!,418.0,24.0,2.0,gabrielcarvajal,01/02/2023,GUADALAJARA,21.0,2721,MEXICO,2023-02-01,Wednesday
15,183736,I have one is best color gradients: Just relea...,361.0,92.0,1.0,pedrojuarez,02/02/2023,OAXACA,12.0,129,MEXICO,2023-02-02,Thursday
16,183737,PIC!!,346.0,115.0,24.0,lucasperes,03/02/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-02-03,Friday
17,183738,hmmm feeling bad today,296.0,93.0,29.0,gabrielcarvajal,04/02/2023,GUADALAJARA,21.0,2721,MEXICO,2023-02-04,Saturday
18,183739,not feeling god right now,315.0,26.0,10.0,galocastillo,05/02/2023,QUITO,332.0,378,ECUADOR,2023-02-05,Sunday
19,183740,Programming is a hot topic!,133.0,145.0,15.0,lucasperes,05/02/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-02-05,Sunday
20,183741,Programming? i love it!,92.0,146.0,1.0,galocastillo,05/02/2023,QUITO,332.0,378,ECUADOR,2023-02-05,Sunday
21,183742,WHAT???,255.0,73.0,17.0,galocastillo,05/02/2023,QUITO,332.0,378,ECUADOR,2023-02-05,Sunday
22,183743,Amazing video by Leonardo!,432.0,95.0,18.0,lucasperes,06/02/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-02-06,Monday
23,183744,Thanks man!,430.0,143.0,28.0,lucasperes,07/02/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-02-07,Tuesday
24,183745,There is nothing better than programming!,424.0,110.0,29.0,lucasperes,02/03/2023,RIO DE JANEIRO,82.0,351,BRASIL,2023-03-02,Thursday
25,183746,BORED AF,488.0,28.0,27.0,gabrielcarvajal,02/03/2023,GUADALAJARA,21.0,2721,MEXICO,2023-03-02,Thursday
26,183747,I do not know if i like programming or other t...,318.0,58.0,20.0,isabelladasilva,03/03/2023,PORTO ALEGRE,928.0,9918,NaN,2023-03-03,Friday